# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64b47614f0b8bda91bfb2420718d1456665446669bf8b68f640da7ce7534d896c1e1ac9388a637729bbae11a3a780d9a76e757c2cdc01042ebd67dc6e19d2478

test:
  secret_key_base: 7b4d07be49467fb3879e0d13dcae0631c92d2db2467df37e9af8441866f6f1a93fdba562ae84d95cde87449f0b6f6d587d2d08aa564f0d9186a856b796cd8dd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
